services:
  db:
    image: postgres:17.0
    volumes:
      - ./containers/postgresql/data/:/var/lib/postgresql/data/
      # コンテナ内のマウント先はデータの実体のある場所
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # $で.envの環境変数名を指定
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
      # posetgresのデフォルトポートは5432
  
  django:
    build:
      context: ./containers/django/
      args: 
       - USERID=${USERID} #build時にユーザーidを渡してそのユーザーに権限を付与
       - GROUPID=${GROUPID}
    depends_on:
      - "db"
    working_dir: /code/django/UserManagementSystem/
    # プロジェクト開始後にmanage.pyのプロジェクトのディレクトリに変更する
    volumes:
      - ./code/django/:/code/django/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
    ports:
      - "${DJANGO_PORT}:8000"
